@startuml SDtestSend
title "Test: CentralComputerIF::send()"

actor "UART Sniffer" as UART
participant "Test" as Test
participant "CentralComputerIF" as CCIF

loop for i=0x0:i=0xFFFF
    CCIF -> UART : send(i,(i%2 == 0),((i%4))))
end loop

@enduml