@startuml
title Klasse diagram: UC3


class Pumpe {
  _speed : int
  _state : bool
  _GPIO : int

  Pumpe(int GPIO, int speed, bool state)
  setSpeed(int) : void
  setState(bool) : void
  getSpeed() : int
  getState() : bool
}

class Varmelegeme {
  temperatur_ : int
  _state : bool 
  _GPIO : int
  _PIDregulering : PID 

  setTemperatur(int) : void
  setState(bool) : void
}
class PID
{
  _Kp : double
  _Ki : double
  _Kd : double
  _deltaTime : double
  _preError : double
  _minOut : double
  _maxOut : double

  PID(double Kp, double Ki, double Kd, double dt, double preError, double minOut, double maxOut)
  calculate(double setpoint, double measured, double resultBuffer) : int
  setKp(double Kp) : void
  setKi(double Kp) : void
  setKd(double Kp) : void
  getKp(void) : double
  getKi(void) : double
  getKd(void) : double
  getOutput(void) : double
}

class UC3_Reguler {
  String data
  void methods()
}

class En_Sensor_klasse{
  int getMåltData()

}

Varmelegeme - PID
Pumpe "3" - "1" UC3_Reguler
UC3_Reguler - Varmelegeme
UC3_Reguler -- En_Sensor_klasse

@enduml

