@startuml SC_UC3
title Sekvensdiagram Aktuator INIT
participant UC3
collections Pumpe
participant Varmelegeme
participant PID

== Initialization ==
UC3 -> Pumpe : new Pumpe(salt)
UC3 -> Pumpe : new Pumpe(deminiraliseret)
UC3 -> Pumpe : new Pumpe(tømning)
UC3 -> Varmelegeme ++ : new Varmelegeme(XXXX)
Varmelegeme -> PID : new PID(Kp, Ki, Kd, deltaTime, minOut, maxOut)
return


== Release ==
UC3 -> Pumpe !! : delete Pumpe(salt)
UC3 -> Pumpe !! : delete Pumpe(deminiraliseret)
UC3 -> Pumpe !! : delete Pumpe(tømning)
Varmelegeme -> PID !! : delete PID
UC3 -> Varmelegeme !! : delte Varmelegeme

@enduml