@startuml SDtestSensorControllerDriverRead
title "Test: Sensor::Read()"


participant "Test" as Test
participant "Sensor Controller Driver" as SCD
actor "Sensor Controller" as SC 

loop for i=0:1000
    Test -> Test : Write to file : Timestamp Start #i
    Test -> SCD : read(i%4)
    SCD -> SC : Request
    SC --> SCD : Reply
    SCD --> Test : Reply
    Test -> Test : Write to file: Timestamp Stop #i
    Test -> Test : Write to file: Reply 
    Test -> Test : Wait 50ms
end loop


@enduml