@startuml SD_AE_addPsu

Participant Aktuatorenhed as ae
participant "Pumpe\n(Salt)" as sp
participant "Pumpe\n(Tømning)" as tp
actor OS as os
title int Aktuatorenhed::addPsu(double psu)

        ae -> ae : addPsu(psu)
        activate ae
        ae -> ae : double ml = (_volume/(10*_saltKonc))*psu;
            ae -> tp :setDutyCycle(10)
            activate tp
            tp -> tp : _dutyCycle = 10
            ae <-- tp
            deactivate tp
            ae -> tp : setState(true);
            activate tp
            tp -> os : setPWM(GPIO, _dutyCycle)
            tp <-- os
            ae <-- tp
            deactivate tp
        ae -> ae : sleep(ml*0.07)
        ae -> tp : setState(false);
            activate tp
            tp -> os : setPWM(GPIO, 0)
            tp <-- os
            ae <-- tp
            deactivate tp
            ae -> sp : setDutyCycle(90)
            activate sp
            sp -> sp : _dutyCycle = 10
            ae <-- sp
            deactivate sp
            ae -> sp : setState(true);
            activate sp
            sp -> os : setPWM(GPIO, _dutyCycle)
            sp <-- os
            ae <-- sp
            deactivate sp
        ae -> ae : sleep(ml*0.07)
        ae -> sp : setState(false);
            activate sp
            sp -> os : setPWM(GPIO, 0)
            sp <-- os
            ae <-- sp
            deactivate sp
            ae <-- ae : return 0
            deactivate ae

@enduml