@startuml
!pragma teoz true

title "Aflæsning af salinitet sekvens"

actor "Central Computer" as CC
participant "Sensor Controller" as SC
participant "ADC-Blok" as ADC
participant "Salinitetsensor" as saltsensor

{start_com} CC -> SC : Aflæs salinitet
{start_read} SC -> ADC: Multiplex til salinitet
ADC -> saltsensor: Aflæser saltindhold
{end_read} SC -> ADC: Læs ADC  
ADC --> SC: Salinitet
{end_com} SC --> CC: Salinitet


{start_com} <-> {end_com}: 1 sek

{start_read} <-> {end_read}: 800 ms


@enduml
