@startuml SensorKonceptuelSekvens
!pragma teoz true

title "Konceptuel Aflæsning af salinitet"

actor "Central Computer" as CC
participant "Sensor Controller" as SC
participant "ADC-Blok" as ADC

{start_com} CC -> SC : Aflæs salinitet
{read_start} SC -> ADC: Læs kanal med salinitet
{read_slut} ADC --> SC: Salinitet
{end_com} SC --> CC: Salinitet


{start_com} <-> {end_com}: 15 ms
{read_start} <-> {read_slut}: 150 µs
@enduml
