@startuml SD_AE_addWater

Participant Aktuatorenhed as ae
participant _saltPumpe as tp
participant _demiPumpe as sp


title int Aktuatorenhed::addWater(double ml, double currentPsu)


        ae -> ae : addWater(double ml, double currentPsu)
        activate ae
        ae -> ae : double mlSaltvand = (ml/(10*_saltKonc))*currentPsu

            ae -> tp : activatePump(90)
            ae <-- tp
            ae -> sp : activatePump(90)
            ae <-- sp
            ae -> ae : sleep(mlSaltvand*0.04)
            ae -> tp : deactivatePump()
            ae <-- tp     
            ae -> ae : sleep((ml-2*mlSaltvand)*0.04)
            ae -> sp : deactivatePump()
            ae <-- sp
            ae <-- ae : return 0
     deactivate ae
            
            
            

@enduml