@startuml SD_AE_substractPsu

Participant Aktuatorenhed as ae
participant "Pumpe\n(Demineraliseret)" as sp
participant "Pumpe\n(Tømning)" as tp
title int Aktuatorenhed::substractPsu(double amountPsuToSubstract, double currentPsu)


        ae -> ae : substractPsu(amountPsuToSubstract, currentPsu)
        activate ae
            ae -> ae : ml = (volume/currentPsu)*amountPsuToSubstract
            ae -> tp : activatePump(90)
            ae <-- tp
            ae -> ae : sleep(ml*0.044)
            ae -> tp : deactivatePump()
            ae <-- tp
            ae -> tp : activatePump(90)
            ae <-- tp
            ae -> ae : sleep(ml*0.044)

            ae -> tp : deactivatePump()
            ae <-- tp
            ae <-- ae : return 0
     

@enduml