@startuml SD_AE_substractPsu

Participant Aktuatorenhed as ae
participant "_demiPumpe" as dp
participant "_toemPumpe" as tp
title int Aktuatorenhed::substractPsu(double amountPsuToSubstract, double currentPsu)


        ae -> ae : substractPsu(amountPsuToSubstract, currentPsu)
        activate ae
            ae -> ae : ml = (volume/currentPsu)*amountPsuToSubstract
            ae -> tp : activatePump(90)
            ae <-- tp
            ae -> ae : sleep(ml*0.044)
            ae -> tp : deactivatePump()
            ae <-- tp
            ae -> dp : activatePump(90)
            ae <-- dp
            ae -> ae : sleep(ml*0.044)

            ae -> dp : deactivatePump()
            ae <-- dp
            ae <-- ae : return 0
     

@enduml