@startuml SD_AE_psuToMl
title double Aktuatorenhed::psuToMl(double psu, double currentPsu, double volume)
participant Aktuatorenhed as ae

ae -> ae : psuToMl(psu, currentPsu, volume)
activate ae

ae <-- ae :   return (volume/currentPsu)*psu;
deactivate ae

@enduml