@startuml SD_AE_addPsu

Participant Aktuatorenhed as ae
participant "_saltPumpe" as sp
participant "_toemPumpe" as tp
title int Aktuatorenhed::addPsu(double amountPsuToAdd)

        ae -> ae : addPsu(amountPsuToAdd)
        activate ae
        ae -> ae : double ml = (_volume/(10*_saltKonc))*amountPsuToAdd
        ae -> tp : activatePump(10)
        ae <-- tp
        ae -> ae : sleep(ml*0.07)
        ae -> tp : deactivatePumpe()
        ae <-- tp
        ae -> sp : activatePump(10);
        ae <-- sp
        ae -> ae : sleep(ml*0.07)
        ae -> sp : deactivatePump();
        ae <-- sp
        ae <-- ae : return 0
            deactivate ae

@enduml