@startgantt
project starts the 2020/09/07
[Last update] happens 2020/10/07 and is colored in #AAF

saturday are closed
sunday are closed

-- FASER I PROJEKTET --

[Projektdefinering] as [PD] starts the 2020/09/07 and ends at 2020/09/17

[Risk assesment & mitigation] as [RA] starts the 2020/09/17
[RA] ends 2020/10/07 and is colored in Salmon
[Kravspecifikation] as [KravSpek] starts the 2020/09/23
[KravSpek] lasts 5 days

[Systemarkitektur] as [SysArch] starts at [KravSpek]'s end
[SysArch] lasts 5 days

[Implementering og Test] as [ImpTest] starts at [SysArch]'s end
[ImpTest] lasts 5 days

[Initial development] as [Init] starts the 2020/10/08 
[Init] ends 2020/10/20  and is colored in DarkSalmon

[Development] as [Dev] starts the 2020/10/21 
[Dev] ends 2020/12/09 and is colored in Orchid

[Process og Metode] as [Process] starts the 2020/12/04 
[Process] lasts 7 days and is colored in DarkSalmon

[Closure] as [Clo] starts the 2020/12/10
[Clo] ends 2020/12/17 and is colored in OrangeRed

[Deadline] happens 2020/12/17

-- Reviews --
[Review #1 udført] is colored in Red and happens 2020/10/26 
[Review #2 udført] is colored in Red and happens 2020/12/03 

-- Workshops --
[Git workshop] happens 2020/09/17
[Redmine workshop] happens 2020/09/24
[Websocket workshop] happens 2020/10/01
[Systematic Git workshop] starts the 2020/10/21 and lasts 2 days

-- Belastning fra andre kurser --
' [MSE øvelse 1] happens 2020/09/14
' [MSE øvelse 2] happens 2020/09/28
' [MSE øvelse 3] happens 2020/10/05
[GFV 1] happens 2020/10/06
[GFV 2] happens 2020/11/10
[GFV 3] happens 2020/11/24

[HAL 2] happens 2020/09/17
[HAL 3] happens 2020/09/24
[HAL 4] happens 2020/10/08
[HAL 5] happens 2020/10/29
[HAL 6] happens 2020/11/12
[HAL 7] happens 2020/11/26
[HAL 8+9] happens 2020/12/10

[EFYS Øvelse 1] happens 2020/09/30
[EFYS Øvelse 2] happens 2020/11/04
[EFYS Øvelse 3] happens 2020/12/02

[EFYS delprøve 1] starts 2020/09/30 and ends 2020/10/06
[EFYS delprøve 2] starts 2020/11/04 and ends 2020/11/10
[EFYS delprøve 3] starts 2020/12/02 and ends 2020/12/08

[DSB Aflevering 1] happens 2020/09/22
[DSB Aflevering 2] happens 2020/10/27
[DSB Aflevering 3] happens 2020/11/17
[DSB Aflevering 4] happens 2020/12/12


2020/10/12 to 2020/10/16 are colored in LightBlue
@endgantt
