@startuml
!pragma teoz true

title "Aflæsning"

actor "Central Computer" as CC
participant "Sensor Controller" as SC
participant "ADC-Blok" as ADC

{start_com} CC -> SC : Request 
alt Request != Vandstand Kritisk
{start_read} SC -> ADC: Sæt Multiplex-signal
ADC -> ADC: Aflæser sensor
{end_read} SC -> ADC: \n\nAflæs
else Request == Vandstand Kritisk
SC -> ADC : \n\n\nAflæs Vandstandsalarm
end alt
ADC --> SC: Aflæst værdi
{end_com} SC --> CC: Data + Kontrol

{start_read} <-> {end_read}: 600 ms


@enduml
