@startuml SDtestGetRequest
title "Test: CentralComputerIF::getRequest()"

actor "Central Computer" as CC
participant "Test" as Test
participant "CentralComputerIF" as CCIF
actor "LED" as LED

Test -> CCIF : getRequest()
loop While no request 
CCIF -> CCIF :
end loop
CC -> CCIF : request (according to protocol)
CCIF --> Test : request 
Test -> LED : LED-port = request

@enduml