@startuml
title Konceptuelt Klassediagram for SensorController

class SensorController
class ADCBlokIF
class CentralComputerIF

SensorController - ADCBlokIF
CentralComputerIF - SensorController

@enduml