@startuml StatiskKlassediagramforSensorController
title Statisk Klassediagram for SensorController

class SensorController{
    +Init() : void
    +Run() : void
    +Sleep() : void
}
class ADCBlokIF{
    +read(int sensorNummer) : uint16 value
    -databits_[4]
}
class CentralComputerIF{
    +getRequest() : int sensorNo
    +send(uint16 value) : void
}


ADCBlokIF --> SensorController
CentralComputerIF -> SensorController

@enduml