@startuml
title Statisk Klassediagram for SensorController

class SensorController{
    +Init() : void
    +Run() : void
}
class ADCBlokIF{
    +multiplex(int sensorNo) : void
    +read() : uint16 value
    -multiplexProtokol_[4]
}
class CentralComputerIF{
    +getRequest() : int sensorNo
    +send(uint16 value) : void
}
class Timer{
    wait(int timeInMs) : void
}

ADCBlokIF --> SensorController
CentralComputerIF -> SensorController
SensorController <- Timer

@enduml