@startgantt
project starts the 2020/09/07
[Last update] happens 2020/10/07 and is colored in #AAF

saturday are closed
sunday are closed

-- FASER I PROJEKTET --

[Projektdefinering] as [PD] starts the 2021/02/01 and ends at 2020/02/12
[Krav] as [Krav] starts the 2021/02/15 and ends at 2021/03/01
[Strukturering] as [Strukturering] starts the 2021/03/01 and ends at 2021/03/15
[Analyse] as [Analyse] starts the2021/03/15 and ends at 2021/03/29
[Design] as [Design] starts the 2021/03/29 and ends at 2021/04/19
[Implementering] as [Implementering] starts the 2021/04/19 and ends at 2021/05/10
[Rapport] as [Rapport] starts the 2021/05/10 and ends at 2021/05/28


@endgantt
