@startgantt
project starts the 2021/02/01

saturday are closed
sunday are closed

-- FASER I PROJEKTET --

[Projektdefinering] as [Projektdefinering] starts the 2021/02/01 and ends at 2021/02/12
[Krav] as [Krav] starts the 2021/02/26 and ends at 2021/03/05
[Strukturering] as [Strukturering] starts the 2021/03/01 and ends at 2021/03/01	2021/03/12
[Analyse] as [Analyse] starts the 2021/03/15 and ends at 2021/03/26
[Design] as [Design] starts the 2021/03/05 and ends at 2021/04/16
[Implementering] as [Implementering] starts the 2021/04/19 and ends at 2021/05/07
[Rapport] as [Rapport] starts the 2021/05/10 and ends at 2021/05/21

[Projektdefinering deadline] happens at 2021/02/19
[Krav deadline] happens at 2021/03/05
[Strukturering deadline] happens at 2021/03/19
[Analyse deadline] happens at 2021/04/02
[Design deadline] happens at 2021/04/23
[Implementering deadline] happens at 2021/05/14
[Rapport deadline] happens at 2021/05/21





@endgantt
