@startuml

title Sensor Timing

concise "ADC-Blok" as ADC
concise "Sensor Controller" as SC
concise "Central Computer" as CC

@-200
CC is {-}
SC is {-}
ADC is {-}
@0
CC is Request
SC is Listening
ADC is {-}
@800
CC is Waiting
SC is Request
ADC is Listening
@1000
SC is Listening 
ADC is Response
@15000



@enduml