@startuml

@startuml
!pragma teoz true

title "Sekvens SensorCom"

actor "Central Computer" as CC
participant "Sensor Controller" as SC

{start_com} CC -> SC : Request
SC -> SC : 
{end_com} SC-->CC : Data
SC-->CC:Kontrol
SC --> CC: Checksum

{start_com} <-> {end_com}: 1 sek

{start_read} <-> {end_read}: 800 ms


@enduml