@startuml CD_SensorControllerDriver
title SensorControllerDriver Klassediagram

class Sensor{
    +Sensor(int sensorNumber, string configPath)
    +read() : double
    +readRaw() : uint16_t
    -setConfig(h) : int
    -setupUART() : int
    -sendRequest(int fd) : int
    -receiveAnswer(int fd, uint16_t &value) : int
    ~Sensor()
    -sensorNumber_ : int
    -configPath_ : string
    -configEditTime_ : int
    -SCT_ : sensorConvertionTable
}

class sensorConvertionTable <<Struct>>{
    -Offset_ : double
    -Factor_ : double
}

Sensor -- sensorConvertionTable

@enduml