@startuml CD_SensorControllerDriver
title SensorControllerDriver Klassediagram

class Sensor{
    +Sensor(int sensorNumber, string configPath)
    +read() : double
    -setConfig(h) : int
    -setupUART(int baud, int parity, int wordlength) : int
    ~Sensor()
    -_sensorNumber : int
    -_configPath : string
    -_configLastReadTimestamp : int
    -_sensorConvertionTable : sensorConvertionTable
    -_UARTfiledescriptor : int
}

class sensorConvertionTable <<Struct>>{
    -_Offset : double
    -_Factor : double
}

Sensor -- sensorConvertionTable

@enduml