@startuml SD_SensorControllerRead

title Sensor::read() : double

skinparam MaxMessageSize 150

actor Main as Main
participant Sensor as SD
participant "UART Driver" as UART
actor SensorController as SC #red


Main -> SD : read()

SD -> SD : setConfig()

loop <u>do</u> while \n(Attempt <= 3) \nOR \n(Kontrol+Request =! Checksum) \nOR \n(Reply == null)
    opt Attempt > 1
        SD -> SD : uSleep(20ms)
    end opt
    SD -> SD : Attempt++
    SD -> UART : Send Request
    SD -> SD : Sleep(10 ms)
    SD -> UART : Read reply
    opt reply == null
        SD -> SD : uSleep(50 ms)
        SD -> UART : Read reply
    end opt
    UART --> SD : Data, Kontrol, Checksum
end loop

alt Kontrol+Request == Checksum \nAND \nReply != null
SD --> Main : Data*_sensorConvertionTable[sensorNumber].Factor + _sensorConvertionTable[sensorNumber].Offset
else 
SD --> Main : 0
end alt


@enduml