@startuml SD_SensorControllerDriverSetConfig

title Sensor::setConfig() : int

skinparam MaxMessageSize 150

participant Main as Main
participant Sensor as SD
database configFile as config

Main -> SD : setConfig()
alt config file updated
SD -> config : Open
opt Open failed
SD --> Main : Fail
end
SD -> config : Get factor and offset for objects sensorNumber
SD -> SD : Set Factor and Offset
SD --> Main : Ok
else 
SD --> Main : File not updated 
end alt



@enduml