@startuml rateLimit

participant Aktuatorenhed as a
participant PI as p

a -> p : rateLimiter() 						
alt if (_newSetpoint - _oldSetpoint > 0.25)		
	p -> p : _setpoint = _oldSetpoint + 0.25\n_oldSetpoint = _setpoint
else
	p -> p : _setpoint = _newSetpoint
end
a <-- p 

@enduml