@startuml ADCBlokRead
title void ADCBlokIF::Read(int sensorNummer)

skinparam MaxMessageSize 500

actor sensorController as SC #red
participant ADCBlokIF as ADCIF
actor ADCBlok as ADC

SC -> ADCIF : read(sensorNumber)
ADCIF -> ADCIF : request[0] = (1 << 1) | (1 << 2)
ADCIF -> ADCIF : request[1] = (channel << 6)
ADCIF -> ADCIF : request[2] = 0bFF
ADCIF -> ADC : Slave select = 1
ADCIF -> ADC : Spi transaction (request)
ADC --> ADCIF : Spi transaction (answer)
ADCIF --> SC : (answer[1] & 0xF) << 8 \n+ \nanswer[2] 

@enduml